<div class="msg msg-error msg-error-501">
    <div><?php echo $this->translate('Error501Description!HTML!'); ?></div>
    <div><?php echo $this->translate($this->msg); ?></div>
</div>
<script type="text/javascript" language="javascript">
    $('<div />')
        .append($('.msg-error-501'))
        .dialog({
            modal: true,
            closeOnEscape: false,
            width: 500,
            resizable: false,
            show: 'bounce',
            title: <?php echo Zend_Json::encode($this->translate('Error501Title')); ?>
         })
         .css('overflow', 'hidden')
         .parent().find('.ui-dialog-titlebar-close').remove();
</script>