<div id="thumbs" class="navigation">
    <ul class="thumbs noscript">
        <li>
            <a class="thumb" href="/uploads/realestateproposal/27.jpeg" rel="lightbox[roadtrip]">
                <img src="/uploads/realestateproposal/27_thumb.jpeg" longdesc="http://www.example.com" alt="Description of the image 2.jpg">
            </a>
        </li>
        <li>
            <a class="thumb" href="/uploads/realestateproposal/28.jpeg" rel="lightbox[roadtrip]">
                <img src="/uploads/realestateproposal/28_thumb.jpeg" longdesc="http://www.example.com" alt="Description of the image 2.jpg">
            </a>
        </li>
    </ul>
</div>
