
<script type="text/javascript" language="javascript">
    $(document).ready(function(){
        var galleries = $('.ad-gallery').adGallery({
            loader_image: '/img/adGallery/loader.gif'
        });
    });
</script>
<div class="ad-gallery">
    <div class="ad-image-wrapper">
    </div>
    <div class="ad-controls">
    </div>
    <div class="ad-nav">
        <div class="ad-thumbs">
            <ul class="ad-thumb-list">
                <li>
                    <a href="/uploads/realestateproposal/27.jpeg">
                        <img src="/uploads/realestateproposal/27_thumb.jpeg" title="Title for 1.jpg">
                    </a>
                </li>
                <li>
                    <a href="/uploads/realestateproposal/30.jpeg">
                        <img src="/uploads/realestateproposal/30_thumb.jpeg" longdesc="http://www.example.com" alt="Description of the image 2.jpg">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>