<script type="text/javascript">
 $(document).ready(function(){
     $("a[rel^='prettyPhoto']").prettyPhoto({
         theme: 'facebook',
         slideshow:5000,
         autoplay_slideshow:true
     });
 });
</script>
<a href="/uploads/realestateproposal/27.jpeg" rel="prettyPhoto[pp_gal]" title="You can add caption to pictures."><img src="/uploads/realestateproposal/27_thumb.jpeg" width="60" height="60" alt="Red round shape" /></a>
<a href="/uploads/realestateproposal/30.jpeg" rel="prettyPhoto[pp_gal]"><img src="/uploads/realestateproposal/30_thumb.jpeg" width="60" height="60" alt="Nice building" /></a>
