<script type="text/javascript" language="javascript">
    page = $.extend(page, {
        init: function() {
            var self = this;
            self.constructor.prototype.init.call(self);

            self.buildToolbars();
            $('#page-toolbar .ui-button').button('disable');
        },
        buildToolbars: function() {
            var self = this,
                buttons = {};
            <?php if ($this->acl->assert($this->aclResource, 'edit')) { ?>
            buttons[<?php echo Zend_Json::encode($this->translate('CreateCommand')); ?>] = {
                id: 'action-create',
                icon: '/img/icons/24x24/add.gif',
                action: function() {
                    $('<div />').iwindow({
                        title: <?php echo Zend_Json::encode($this->translate('NewRole')); ?>,
                        url: '/administration/roles/item/__command__/<?php echo md5('edit' . Zend_Session::getId()); ?>',
                        maximized: true,
                        bubble: true
                    });
                }
            };
            <?php } ?>
            <?php if ($this->acl->assert($this->aclResource, 'remove')) { ?>
            buttons[<?php echo Zend_Json::encode($this->translate('DeleteCommand')); ?>] = {
                id: 'action-remove',
                icon: '/img/icons/24x24/remove.gif',
                action: function() {
                    $('<div />')
                        .html(<?php echo Zend_Json::encode($this->translate('DeleteRoleConfirm!HTML!')); ?>)
                        .dialog({
                            title: <?php echo Zend_Json::encode($this->translate('DeleteAction')); ?>,
                            modal: true,
                            resizable: false,
                            width: 400,
                            buttons: {
                                <?php echo Zend_Json::encode($this->translate('CancelCommand')); ?>: function() {
                                    $(this).dialog('destroy').remove();
                                },
                                <?php echo Zend_Json::encode($this->translate('DeleteCommand')); ?>: function() {
                                    var dialog = $(this);
                                    $.ajax({
                                        async: false,
                                        url: '/administration/roles/delete',
                                        data: {'items[]': $('#list').getGridParam('selarrrow')},
                                        type: 'POST',
                                        beforeSend: function() {
                                            $('<div />')
                                                .addClass('ui-dialog-loader')
                                                .prependTo(dialog.children().css({opacity: 0}).end());
                                        },
                                        complete: function() {
                                            $('#list').trigger('reloadGrid');
                                            dialog.dialog('destroy').remove();
                                        }
                                    })
                                }
                            }
                        });
                }
            };
            <?php } ?>
            <?php if ($this->acl->assert($this->aclResource, 'edit')) { ?>
            buttons[<?php echo Zend_Json::encode($this->translate('EditCommand')); ?>] = {
                id: 'action-edit',
                icon: '/img/icons/24x24/edit.gif',
                action: function() {
                    var rowId = $('#list').getGridParam('selrow');
                    var row = $('#' + rowId);
                    $('<div />').iwindow({
                        title: self.getRoleTitle(rowId),
                        url: '/administration/roles/item/id/' + rowId + '/__command__/<?php echo md5('edit' . Zend_Session::getId()); ?>',
                        maximized: true,
                        bubble: true
                    });
                }
            };
            <?php } else { ?>
            buttons[<?php echo Zend_Json::encode($this->translate('ExploreCommand')); ?>] = {
                id: 'action-edit',
                icon: '/img/icons/24x24/explore.gif',
                action: function() {
                    var rowId = $('#list').getGridParam('selrow');
                    $('<div />').iwindow({
                        title: self.getRoleTitle(rowId),
                        url: '/administration/roles/item/id/' + rowId,
                        maximized: true,
                        bubble: true
                    });
                }
            };
            <?php } ?>
            self.createToolbar(buttons);
            self.createGridToolbar(
                <?php echo Zend_Json::encode($this->translate('RefreshCommand')); ?>,
                false,
                false,
                false
            );
        },
        beforePageLayout: function() {
            var self = this;

            var grid = $('#list');
            grid.setGridParam({
                loadBeforeSend: function() {
                    $('#page-toolbar .ui-button').button('disable');
                },
                afterInsertRow: function(rowid, rowdata) {
                    if (typeof rowid == 'object') {
                        rowid = rowdata;
                        rowdata = grid.getRowData(rowid);
                    }

                    var row = grid.find('#' + rowid);

                    row.find('td:eq(1)').each(function() {
                        $(this).wrapInner('<a />').find('a').attr('href', '/administration/roles/item/id/'
                                     + rowid + '/__command__/<?php echo md5('edit' . Zend_Session::getId()); ?>')
                           .click(function() {
                                $('<div />').iwindow({
                                    title: self.getRoleTitle(rowid),
                                    url: $(this).attr('href'),
                                    maximized: true,
                                    bubble: true
                                });
                                return false;
                           });
                    });
                    row.find('td:eq(3)').each(function() {
                        $(this).wrapInner('<a />').find('a').attr('href', '/administration/departments/item/id/' + rowdata.DepartmentId).click(function() {
                            $('<div />').iwindow({
                                title: <?php echo Zend_Json::encode($this->translate('Department')); ?> +
                                       ' "' + rowdata.Department + '"',
                                url: $(this).attr('href'),
                                maximized: true,
                                bubble: true
                            });
                            return false;
                        });
                    });
                    row.find('td:eq(5)').each(function() {
                        $(this).wrapInner('<a />').find('a').attr('href', '/administration/specializations/item/id/' + rowdata.SpecializationId).click(function() {
                            $('<div />').iwindow({
                                title: <?php echo Zend_Json::encode($this->translate('Specialization')); ?> +
                                       ' "' + rowdata.Specialization + '"',
                                url: $(this).attr('href'),
                                maximized: true,
                                bubble: true
                            });
                            return false;
                        });
                    });
                },
                gridComplete: function() {
                    self.setActionsToolbarButtonsState();
                    self.setGridToolbarButtonsState();
                },
                onSelectRow: function() {
                    var selectedRowId = $('#list').getGridParam('selrow');
                    self.setActionsToolbarButtonsState();
                    if ($('#' + selectedRowId).find('.tc-repository').size()) {
                        $('#action-download').button('enable');
                    } else {
                        $('#action-download').button('disable');
                    }
                    self.setGridToolbarButtonsState();
                }
            });

            self.constructor.prototype.beforePageLayout.call(self);
        },
        afterPageLayout: function() {
            var self = this;
            self.constructor.prototype.afterPageLayout.call(self);

            $('.ui-jqgrid-filter .ui-jqgridfilter-edit .form-element-item').css({width: '500px'});

            var popupPhrases = {
                cancel: <?php echo Zend_Json::encode($this->translate('CancelCommand')); ?>,
                select: <?php echo Zend_Json::encode($this->translate('SelectCommand')); ?>,
                breakConnection: <?php echo Zend_Json::encode($this->translate('BreakConnectionCommand')); ?>,
                alert: <?php echo Zend_Json::encode($this->translate('Alert')); ?>,
                noSelection: <?php echo Zend_Json::encode($this->translate('NoObjectSelectedLinkingConfirm!HTML!')); ?>,
                ok: <?php echo Zend_Json::encode($this->translate('Ok')); ?>
            };
            $('#departmentTitleFilter').width('480px').linkableField({
                visibleParam: 'title',
                basicUrl: '/administration/departments',
                idHolder: '#departmentIdFilter',
                popupPhrases: popupPhrases
            });
            $('#specializationTitleFilter').width('480px').linkableField({
                visibleParam: 'title',
                basicUrl: '/administration/specializations',
                idHolder: '#specializationIdFilter',
                popupPhrases: popupPhrases
            });
        },
        getRoleTitle: function(rowid) {
            return <?php echo Zend_Json::encode($this->translate('Role')); ?> + ' "' + $.trim($('#list').getRowData(rowid).Title.replace(/<[^>]*>/g, "")) + '"'
        }
    });
</script>