<noscript><div class="msg msg-error msg-error-nojs"><?php echo $this->translate('NoJavaScriptEnnableAlert'); ?></div></noscript>
<div id="authorization-dialog" class="ui-dialog ui-widget ui-widget-content ui-corner-all" style="display:none">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all">
        <?php echo $this->escape($this->translate('Authorization')); ?>
    </div>
    <div class="ui-dialog-content ui-widget-content">
        <div id="authorization-dialog-maincontanet">
            <div id="authorization-dialog-maincontanet-apptitle">
                <?php echo $this->escape($this->translate('ApplicationTitleLong')); ?>
            </div>
            <div id="authorization-dialog-maincontanet-appsubtitle">
                <?php echo $this->escape($this->translate('AuthorizationInvitation')); ?>
            </div>
            <div id="authorization-dialog-maincontanet-formcontainer" class="ui-widget ui-widget-content ui-corner-all">
                <?php echo $this->form; ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript">
    var dialog = $('#authorization-dialog');
    dialog
        .css({
            position: 'absolute',
            top: '50%',
            left: '50%',
            marginTop: '-' + parseInt(dialog.height()/2) + 'px',
            marginLeft: '-' + parseInt(dialog.width()/2) + 'px'
        })/*
        .show('clip', function(){
            $('#username').focus();
        })*/;
    dialog.css('display','block');
    $('#username').focus();

</script>