<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
    header('Content-Type: text/html; charset=UTF-8');
?>
<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta() ?>
        <link type="image/x-icon" rel="shortcut icon" href="/favicon.ico" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->jQuery(); ?>
    </head>
    <body>
        <?php echo $this->layout()->content ?>
    </body>
</html>